complete -c portkill -f
complete -c portkill -n '__fish_use_subcommand' -a 'list kill doctor completion monitor tree scan benchmark history menu'
complete -c portkill -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'
complete -c portkill -l help -d 'Show help'
complete -c portkill -l version -d 'Show version'
complete -c portkill -l verbose -d 'Verbose output'
complete -c portkill -l quiet -d 'Quiet output'
complete -c portkill -l safe -d 'Protect system processes'
complete -c portkill -l force -s f -d 'Use SIGKILL'
complete -c portkill -l dry-run -s n -d 'Preview without killing'
complete -c portkill -l interactive -s i -d 'Ask before each kill'
complete -c portkill -l detailed -s d -d 'Show detailed output'
complete -c portkill -l docker -d 'Include Docker containers'
complete -c portkill -l json -d 'Output JSON'
complete -c portkill -l no-color -d 'Disable colors'
complete -c portkill -l yes -s y -d 'Skip confirmation'
complete -c portkill -l no-confirm -d 'Skip confirmation'
